# Site settings
title: xvblack notes
email: xvblue@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Something wrote here...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xvblack.github.io" # the base hostname & protocol for your site
github_username:  xvblack

# Build settings
markdown: kramdown
